### ISSUE TITLE
Error: Request failed with status code 404 (axios error)

### ISSUE THREAD

**Issue by JayThibs** [omerdn1/otter.ai-api#22]
Hey, thanks for creating this package.

Unfortunately, I can't grab any conversations from otter.ai. Is it possible that they made changes to the side that breaks the code in this repo? I'm using the following code:

```
const OtterApi = require('otter.ai-api').default;

const otterApi = new OtterApi({
    email: 'email', // Your otter.ai email
    password: 'pw', // Your otter.ai password
});

async function main() {

    await otterApi.init() // Performs login
    await otterApi.getSpeeches(); // Gets all speeches
}

main();
```

I tried for one speech and all. And then I'm getting the following error after a successful login:

```
Successfuly logged in to Otter.ai
/Users/jacquesthibodeau/Desktop/Code/ai-alignment-audio-transcription/otter.ai-api/node_modules/axios/lib/core/createError.js:16
  var error = new Error(message);
              ^

Error: Request failed with status code 404
    at createError (/Users/jacquesthibodeau/Desktop/Code/ai-alignment-audio-transcription/otter.ai-api/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/Users/jacquesthibodeau/Desktop/Code/ai-alignment-audio-transcription/otter.ai-api/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/Users/jacquesthibodeau/Desktop/Code/ai-alignment-audio-transcription/otter.ai-api/node_modules/axios/lib/adapters/http.js:260:11)
    at IncomingMessage.emit (node:events:539:35)
    at endReadableNT (node:internal/streams/readable:1344:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

Then there's a really long json response. But I see this at the end:

```
        'user-agent': [ 'User-Agent', 'axios/0.21.1' ],
        host: [ 'Host', 'otter.ai' ]
      }
    },
    data: { status: 'failed', message: 'Speech not found', code: 13 }
  },
  isAxiosError: true,
  toJSON: [Function: toJSON]
}
```

Any ideas if this is fixable?

**Comment by omerdn1** [comment]
Hey @JayThibs, I'm sorry for the long delay. I took a long break from coding.
Are you still experiencing this issue?

**Comment by omerdn1** [comment]
Closing this for inactivity. Feel free to revive this if the issue persists.
